### ISSUE TITLE
Difference between `@keyvhq/core` and `keyv` (jaredwray/keyv)?

### ISSUE THREAD

**Issue by inooid** [microlinkhq/keyv#103]
👋   Heya, I am looking to contribute to KeyV, but I am hopelessly confused by the existence of two similar packages (even the similarities in README's are uncanning) between your [`@keyvhq/core`](https://github.com/microlinkhq/keyv) and [`keyv`](https://github.com/jaredwray/keyv). Both libraries' cores are well maintained and regularly updated, what's the decision behind creating another package rather than contributing to the existing `keyv` package directly?

Before contributing to either packages, I'd like to know which one to pour my time into 👍 

Keep up the good work!

**Comment by Kikobeats** [comment]
Hello

We forked the original keyv to resolve all the issues, provide types definition, extend the API, add documentation, etc.

We update it almost every week.

🙂
