### ISSUE TITLE
Ability to create a KeyvRedis with an existing Redis instance in Typescript

### ISSUE THREAD

**Issue by talzion12** [microlinkhq/keyv#126]
In the [readme for keyv redis](https://github.com/microlinkhq/keyv/blob/master/packages/redis/README.md) it says that a `KeyvRedis` can be constructed as follows:
```ts
const KeyvRedis = require('@keyvhq/redis')
const Keyv = require('@keyvhq/core')
const Redis = require('ioredis')

const redis = new Redis('redis://user:pass@localhost:6379')
const keyv = new Keyv({ store: new KeyvRedis(redis) })
```

However this code doesn't compile with Typescript, nor should it according to [index.d.ts](https://github.com/microlinkhq/keyv/blob/master/packages/redis/src/index.d.ts).

Looking at the JS I think the code does work although I didn't test this. IMO the only change that is needed is to add a constructor to the [index.d.ts](https://github.com/microlinkhq/keyv/blob/master/packages/redis/src/index.d.ts) file. In fact there seem to be 2 identical constructors in [index.d.ts](https://github.com/microlinkhq/keyv/blob/master/packages/redis/src/index.d.ts), I assume one of them was supposed to be the constructor to create a `KeyvRedis` with a `Redis` instance.

**Comment by Kikobeats** [comment]
Thanks for reporting; Can you make a PR for this? 🙂

**Comment by talzion12** [comment]
Sure.
