### ISSUE TITLE
bug: KeyvRedis key prefix namespace behavior is not consistent with Keyv (core)

### ISSUE THREAD

**Issue by titanism** [microlinkhq/keyv#158]
Duplicate of <https://github.com/jaredwray/keyv/issues/700>.  This applies for other adapters besides Redis.  The default behavior should match the behavior that comes out of the box in core Keyv regarding namespaces and key prefixing.  Otherwise you run into having to create multiple connections because `ioredis` does not support that (see <https://github.com/luin/ioredis/issues/983>).

It would be helpful to have notices as to what makes this repo different than @jaredwray's.  It says this one is maintained, but there are recent commits to that repo too.

In any case, I'd love to have contributor access on GH and npm so I can help fix this stuff.  I use np for version releases and abide by semver.

**Comment by jaredwray** [comment]
@titanism - this is a fork of the the main Keyv and causes confusion with many. We are also planning a fully rebuilt redis coming in the next 2-3 months on the main Keyv repo.

**Comment by jaredwray** [comment]
Happy for you to contribute changes anytime and we review changes as fast as we can. We usually release very 10-14 days.

**Comment by jaredwray** [comment]
@titanism - note this thread is on a forked version of keyv. Lets keep any requests or concerns on the main repo here: https://github.com/jaredwray/keyv

**Comment by Kikobeats** [comment]
Hum, It sounds a bit strange to me. I'm reusing Redis instance in my current project setup.

Can you isolate the bug into a reproducible repo or test? then could be easy to fix it.

In fact, I reported that years ago: https://github.com/jaredwray/keyv/pull/102

That's one of the reason we decided to forked it and take care.

**Comment by Kikobeats** [comment]
What was actually buggy is the example on docs; Now it should be reflected how to reuse Redis instance properly.

Also, I re-wrote the test in a more readable way to showcase how the store is reused:

https://github.com/microlinkhq/keyv/blob/d065f51d57d6d2a32a939c4bcdfc901a50954177/packages/redis/test/index.js#L21

**Comment by jaredwray** [comment]
@titanism - if you are planning to use the microlinkhq version please work with Kikobeats on it and work in this repo and issues and you can leave me off.
