### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by Jytesh** [microlinkhq/keyv#4]
> Will enable autocompletion in supported text editors/IDEs.
Previous discussion in [#22](https://github.com/lukechilds/keyv/issues/22)
To prevent definitions going out of sync we should either include some sort of test to validate the definitions or alternatively they be generated from our source (annotated comments?).

From [#25](https://github.com/lukechilds/keyv/issues/25)

Better to add the typings from PR: [#30](https://github.com/lukechilds/keyv/pull/30) instead of translating the whole thing to typescript (IMO)

**Comment by Jytesh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/keyv/index.d.ts

This is also a good reference

**Comment by Kikobeats** [comment]
I think keeping types at `DefinitelyTyped` repository it's great because it allows any member of the community to edit it without releasing a new keyv version.

Also I think that's a good practice inside TypeScript community, e.g.,
https://github.com/browserless/chrome/blob/master/base/Dockerfile#L85

**Comment by Jytesh** [comment]
Alright then! Any idea how to test those, and have a notif or something when the typings go out of sync?

**Comment by Jytesh** [comment]
Alright then! Any idea how to test those, and have a notif or something when the typings go out of sync?

**Comment by Jytesh** [comment]
And I think the types at `@types/keyv` only provide types for `keyv` by default, do we need to enable/configure something to make `@keyvhq/keyv` use the same typings

**Comment by Jytesh** [comment]
> And I think the types at `@types/keyv` only provide types for `keyv` by default, do we need to enable/configure something to make `@keyvhq/keyv` use the same typings

@Kikobeats ^^
