### ISSUE TITLE
Documentation for KeyvSqlite shows invalid constructor arguments

### ISSUE THREAD

**Issue by pricecomstock** [microlinkhq/keyv#91]
The README on [this page](https://github.com/microlinkhq/keyv/tree/master/packages/sqlite) shows that you can instantiate KeyvSqlite like this:

```javascript
const KeyvSqlite = require('@keyvhq/sqlite')
const Keyv = require('@keyvhq/core')

const keyv = new Keyv({ 
  store: new KeyvSqlite('sqlite://path/to/database.sqlite', {
    table: 'cache',
    busyTimeout: 10000
  })
})
```

I was not getting persistence doing this. After digging, I realized it was silently failing and using an in memory database, because the [constructor](https://github.com/microlinkhq/keyv/blob/master/packages/sqlite/src/index.js) looks like this:

```javascript
class KeyvSqlite extends KeyvSql {
  constructor (options) {
    options = Object.assign(
      {
        dialect: 'sqlite',
        uri: 'sqlite://:memory:'
      },
      options
    )
    options.db = options.uri.replace(/^sqlite:\/\//, '')

// more stuff here that I cut out
}
```

The constructor only takes the options object, so you actually need to instantiate it like this:
```javascript
new Keyv({
  store: new KeyvSqlite({
    uri: "sqlite://data.db"
  })
})
```

**Comment by Kikobeats** [comment]
ops, sorry for that. Can you make a PR to clarify how to use it? 🙂

**Comment by pricecomstock** [comment]
@Kikobeats yeah I could do a PR.

Would you rather have
A. the documentation updated to show the correct way to do this
B. (breaking) changes to the sqlite constructor to make it consistent with the others?
